feat: Adding ToggleSwitch Material 3 Styles
unoplatform/Uno.Themes pull request #1031
Opened 2023-06-14 15:48 UTC by eriklimakc

﻿GitHub Issue: #806

## PR Type

What kind of change does this PR introduce?
- Feature

## Description

## PR Checklist 
Please check if your PR fulfills the following requirements:

- Commits must be following the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- [X] Tested UWP
- [ ] Tested iOS
- [X] Tested Android
- [X] Tested WASM
- [ ] Tested MacOS
- [X] Contains **No** breaking changes
  > If the pull request contains breaking changes, commit message must contain a detailed description of the action to take for the consumer of this library. As explained by the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)

## Other information

## Internal Issue (If applicable):

2023-06-14 15:53 UTC, eriklimakc commented
Currently getting a strange behavior on Skia GTK, may be related to https://github.com/unoplatform/uno/issues/8636


https://github.com/unoplatform/Uno.Themes/assets/114886335/bb787170-3e0e-486d-bce9-61fea5ab9550

2023-06-16 14:26 UTC, agneszitte commented
> Currently getting a strange behavior on Skia GTK, may be related to [unoplatform/uno#8636](https://github.com/unoplatform/uno/issues/8636)
> 
>  gtk.m3.toggleswitch.mp4

@eriklimakc / @kazo0 Outside of GTK, are they additional issues with the current changes on the other platforms?
On Wasm I can see this issue when loading the page :
![image](https://github.com/unoplatform/Uno.Themes/assets/16295702/0ba7e6c2-68b8-4674-b610-c1eeab9de66e)

2023-06-16 14:28 UTC, eriklimakc commented
> > Currently getting a strange behavior on Skia GTK, may be related to [unoplatform/uno#8636](https://github.com/unoplatform/uno/issues/8636)
> > gtk.m3.toggleswitch.mp4
> 
> @eriklimakc / @kazo0 Outside of GTK, are they additional issues with the current changes on the other platforms? On Wasm I can see this issue for example when loading the page : ![image](https://user-images.githubusercontent.com/16295702/246444773-0ba7e6c2-68b8-4674-b610-c1eeab9de66e.png)

Yes, I'm currently working to fix this one. When `IsOn` is `true` the thumb starts in the wrong position for WASM/Android/GTK.

2023-06-19 12:36 UTC, eriklimakc commented
Need this fix to proceed https://github.com/unoplatform/uno/issues/12643

2023-06-19 12:47 UTC, kazo0 commented
@Xiaoy312 is this at all related to https://github.com/unoplatform/uno/pull/12054?

2023-06-21 20:27 UTC, agneszitte requested changes
@eriklimakc Seems that there are other issues like these:
- **Visual State circle is off**
  - With current changes on WASM
    ![image](https://github.com/unoplatform/Uno.Themes/assets/16295702/8388f3be-ada5-4664-b194-34963414baf9)
  - On The Figma file
    ![image](https://github.com/unoplatform/Uno.Themes/assets/16295702/b6ab0628-f931-4988-a455-d81616b6afb8)
    
- **Make sure the icon is following the proper design rules for the size**
  - With the current changes on WASM
    ![image](https://github.com/unoplatform/Uno.Themes/assets/16295702/47653541-90d2-4d2d-bf8b-ae7c2ae4378b)
  - On the Figma file
    ![image](https://github.com/unoplatform/Uno.Themes/assets/16295702/6d1de499-1717-4da1-9fe4-a13fa16fa2ca)

- Make sure to use the proper brushes with different opacities for the different visual states
  Example in Figma here for the Visual State circle:
  ![image](https://github.com/unoplatform/Uno.Themes/assets/16295702/7b619953-5f5c-448c-903f-2bc734e79369)

(cc @NVLudwig, @kazo0)

2023-06-21 20:45 UTC, NVLudwig commented
Very happy to see the icons are in there :)
Good comments from @agneszitte I would only add:
1) The animation seems a little fast and "flickery" compared to this https://m3.material.io/components/switch/guidelines#2495f276-189c-4d51-a9df-88e89e8e8185

https://github.com/unoplatform/Uno.Themes/assets/29584087/a47d3631-f68a-4334-a3b9-e4e5cc29d091


2) The spacing between the "thumb" and rail seems off, especially in the disabled states
**Published**
<img width="252" alt="image" src="https://github.com/unoplatform/Uno.Themes/assets/29584087/d84758da-d9a7-4c56-9848-b247e6b454f8">
**Expected**
<img width="169" alt="image" src="https://github.com/unoplatform/Uno.Themes/assets/29584087/9002f463-9035-4498-9998-2e55187a5b21">

2023-06-26 12:08 UTC, eriklimakc commented
# Dark and Light theme issues
It seems we have a problem with brushes when the Theme (Dark/Light) is changed. The colors are not matching.

## OS Theme as LIGHT

When OS theme is Light, it is correct: 
![Light on System Light](https://github.com/unoplatform/Uno.Themes/assets/114886335/e3768773-10d6-48aa-97ec-54047002224e)

If theme is changed to **Dark** on the Sample App we have:
![Dark on System Light](https://github.com/unoplatform/Uno.Themes/assets/114886335/5bf6717a-118e-4d3a-8617-a90a6fa21119)


## OS Theme as DARK

But, if the sample is launched with OS Theme as Dark we have:
![Dark on System Dark](https://github.com/unoplatform/Uno.Themes/assets/114886335/407ff08d-9234-4eab-9eea-d76b4608cab7)


And when theme is changed on the Sample App to **Light**
![Light on System Dark](https://github.com/unoplatform/Uno.Themes/assets/114886335/faad1779-c2f6-4344-9cf8-510bc7fff612)

Does this also happen with other controls?

@agneszitte @kazo0 @Xiaoy312

2023-06-26 12:55 UTC, kazo0 commented
@eriklimakc I believe this is fixed in a PR or is at least a known issue with the sample app, let me check

2023-07-18 17:37 UTC, NVLudwig commented
Toggle Switch not showing at all for Material M3 on Safari

2023-07-19 17:05 UTC, eriklimakc commented
> Toggle Switch not showing at all for Material M3 on Safari

@NVLudwig Did you get an empty screen instead or just the ToggleSwitch control not being displayed?

I tried it on my side on Safari for mac and Safari for iOS and it shows to me:

![toggleswitch_safari_ios](https://github.com/unoplatform/Uno.Themes/assets/114886335/3e9aa6a6-c5cd-47ac-9584-3320bfb3f6fc)
![toggleswitch_safari_mac](https://github.com/unoplatform/Uno.Themes/assets/114886335/2200c26b-6b5f-47d1-b384-36754c0f0a55)

cc @agneszitte @kazo0

2023-07-19 18:23 UTC, NVLudwig commented
@eriklimakc 
I just does not load the toggle switch for Material Tab it does in the Cupertino.

https://github.com/unoplatform/Uno.Themes/assets/29584087/cab17fe8-216e-4a4a-a442-e3edb5ed04a3

2023-07-24 18:06 UTC, eriklimakc commented
# Current Material 3 ToggleSwitch:

## Android
![android](https://github.com/unoplatform/Uno.Themes/assets/114886335/81f048da-005c-420b-8c34-902f6e6d6f3f)

## GTK
![gtk](https://github.com/unoplatform/Uno.Themes/assets/114886335/1dc11c0d-9705-4a40-987f-0ea06416afe8)

## iOS
![ios](https://github.com/unoplatform/Uno.Themes/assets/114886335/dd472c80-911a-4cef-b2b7-8b9db462510c)

## UWP
![uwp](https://github.com/unoplatform/Uno.Themes/assets/114886335/ff2d5ae4-3e80-4098-95da-05adc3cfa15b)

## Wasm
![wasm](https://github.com/unoplatform/Uno.Themes/assets/114886335/2e852fe3-fe7d-41c5-bf0a-c4874b9cba84)

2023-07-24 19:55 UTC, agneszitte commented
@eriklimakc I am still seeing position issues for WASM for example with the latest changes
![image](https://github.com/unoplatform/Uno.Themes/assets/16295702/b123ccac-36a5-4e6b-8754-0531d4af3f35)
(cc @kazo0)

2023-07-24 19:59 UTC, eriklimakc commented
> @eriklimakc I am still seeing position issues for WASM for example with the latest changes ![image](https://user-images.githubusercontent.com/16295702/255699831-b123ccac-36a5-4e6b-8754-0531d4af3f35.png) (cc @kazo0)

For the disabled ones it's related to this issue https://github.com/unoplatform/uno/issues/12643.

cc @kazo0 @Xiaoy312

2023-07-26 13:14 UTC, NVLudwig commented
Very good! @eriklimakc (works on safari in both tabs)

2023-07-26 13:16 UTC, eriklimakc commented
@NVLudwig Thanks, I'm currently trying to fix the thumb shadow that's being clipped in some platforms, then the team can review all the code.

cc @agneszitte @kazo0

2023-07-27 14:19 UTC, NVLudwig commented
Clipping issue with the inactive state Thumb
![image](https://github.com/unoplatform/Uno.Themes/assets/29584087/99341225-4f41-4f55-aab3-f4b76828be11)

2023-07-27 18:39 UTC, iurycarlos commented
Strange, for me it seems correct:

![image](https://github.com/unoplatform/Uno.Themes/assets/6876973/60192f74-462e-476a-926e-313d08f927f5)
![image](https://github.com/unoplatform/Uno.Themes/assets/6876973/8f405119-878e-4bd2-9159-5e3279018063)

2023-07-28 20:40 UTC, NVLudwig commented
I'm still getting strange clipping and it's spcifically happening when using a mouse then clicking and not moving the cursor away from the Control.

When you do this the thumb element goes to "Pressed" state for some reason at the end of the animation (as if you had held your finger down the whole time) and the "thumb" gets clipped every time. It resolves itself when you move the cursor away and the state goes back to "enabled" so you can't repro this in touch.

Here are some exemples

![image](https://github.com/unoplatform/Uno.Themes/assets/29584087/50ba9c2e-660c-456f-904c-30ca9fed4dc4)
![image](https://github.com/unoplatform/Uno.Themes/assets/29584087/a4277398-5726-403f-bd34-39b9b81a2ab4)
![image](https://github.com/unoplatform/Uno.Themes/assets/29584087/38634028-e160-4212-a992-b69808d90333)

Happening on MacOS: 12.3.1 (21E258)
Safari: Version 15.4 (17613.1.17.1.13)

2023-07-28 20:50 UTC, agneszitte commented
> I'm still getting strange clipping and it's spcifically happening when using a mouse then clicking and not moving the cursor away from the Control.
> 
> When you do this the thumb element goes to "Pressed" state for some reason at the end of the animation (as if you had held your finger down the whole time) and the "thumb" gets clipped every time. It resolves itself when you move the cursor away and the state goes back to "enabled" so you can't repro this in touch.
> 
> Here are some exemples
> 
> ![image](https://user-images.githubusercontent.com/29584087/256927909-50ba9c2e-660c-456f-904c-30ca9fed4dc4.png) ![image](https://user-images.githubusercontent.com/29584087/256927940-a4277398-5726-403f-bd34-39b9b81a2ab4.png) ![image](https://user-images.githubusercontent.com/29584087/256927983-38634028-e160-4212-a992-b69808d90333.png)
> 
> Happening on MacOS: 12.3.1 (21E258) Safari: Version 15.4 (17613.1.17.1.13)

Yeah I am not sure what is happening for Safari on mac @NVLudwig as these clipping issues are not reproducible on Chrome Mac.
@jeromelaban are you aware of similar clipping issues for Safari only ?

2023-07-28 21:14 UTC, agneszitte commented
> Yeah I am not sure what is happening for Safari on mac @NVLudwig as these clipping issues are not reproducible on Chrome Mac. @jeromelaban are you aware of similar clipping issues for Safari only ?

Decided with @kazo0 that with @eriklimakc we will create a separate issue for Uno for the clipping issues related to Safari only.
@jeromelaban maybe think it is related to 4K but not sure.

2023-07-29 02:33 UTC, kazo0 approved these changes

2023-07-31 17:30 UTC, agneszitte commented
> Azure Static Web Apps: Your stage site is ready! Visit it here: https://salmon-rock-0cfebe70f-1031.eastus2.azurestaticapps.net

@NVLudwig, can you please re-test Safari Mac with this link that includes the latest changes?
It is fixed normally for the clipping issues even on Safari, the only thing I noticed is that the animation is not as smooth as on Chrome Mac for Safari.

2023-07-31 17:59 UTC, NVLudwig commented
Commented in Teams

2023-07-31 18:00 UTC, Xiaoy312 commented on src/library/Uno.Material/Styles/Controls/v2/ToggleSwitch.xaml
>  					xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
you can trim some of the unused xmlnses here, especially the new ones added in this pr

2023-07-31 18:02 UTC, Xiaoy312 commented on src/library/Uno.Material/Styles/Controls/v2/ToggleSwitch.xaml
> +	<!--Animations-->
mvoe to AnimationConstants.xaml

2023-07-31 18:04 UTC, agneszitte commented
> Commented in Teams

Will open a separate issue for Safari, thanks @NVLudwig

2023-07-31 18:05 UTC, Xiaoy312 commented on src/library/Uno.Material/Styles/Controls/v2/ToggleSwitch.xaml
> +	<!--Converters-->
can you prefix the xkey with the control name?

2023-07-31 19:49 UTC, agneszitte approved these changes

2023-07-31 19:50 UTC, merged

2023-07-31 23:07 UTC, agneszitte commented
@mergifyio backport legacy/2x