fix: checkbox and radiobutton fontweight
unoplatform/Uno.Themes pull request #1161
Opened 2023-08-17 17:51 UTC by Marc-Antoine-Soucy

﻿GitHub Issue: #
[#11428](https://github.com/unoplatform/uno/issues/11428)
## PR Type

What kind of change does this PR introduce?

- Bugfix

## Description

This pr gives the checkbox and the radiobutton text the correct fontfamilly as well as the correct foreground.

From figma: 
```
color: var(--light-on-surface-on-surface-medium-brush, rgba(28, 27, 31, 0.60));
font-feature-settings: 'clig' off, 'liga' off;
/* UNO Semantic/Body Small */
font-family: Roboto;
font-size: 12px;
font-style: normal;
font-weight: 500;
line-height: normal;
letter-spacing: 0.4px;
```
Fontweight 500 => Medium
and OnSurfaceMediumBrush 
![image](https://github.com/unoplatform/Uno.Themes/assets/90481654/29122262-16e7-43ca-985b-d3165adc3327)

## PR Checklist 
Please check if your PR fulfills the following requirements:

- Commits must be following the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- [X] Tested UWP
- [X] Tested iOS
- [X] Tested Android
- [X] Tested WASM
- [ ] Tested MacOS
- [ ] Contains **No** breaking changes
  > If the pull request contains breaking changes, commit message must contain a detailed description of the action to take for the consumer of this library. As explained by the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)

## Other information

Before: 
![image](https://github.com/unoplatform/Uno.Themes/assets/90481654/2153ad6b-d0d7-4171-babc-0c19fab575fc)

Figma: 
![image](https://github.com/unoplatform/Uno.Themes/assets/90481654/ad622c82-2f93-4562-b955-815f74bae8e6)

After:
![image](https://github.com/unoplatform/Uno.Themes/assets/90481654/651374e7-a61c-4625-9426-29462c5f5f69)

## Internal Issue (If applicable):

2023-08-17 17:57 UTC, Marc-Antoine-Soucy commented
The surface medium brush seems to have a higher opacity on figma?

2023-08-18 20:08 UTC, Xiaoy312 commented on src/samples/UWP/Uno.Themes.Samples.Shared/Content/OverviewPage.xaml
these changes (for testing) should not be included

2023-08-18 20:11 UTC, Xiaoy312 commented on src/samples/UWP/Uno.Themes.Samples.Shared/Content/OverviewPage.xaml
why do we need to explicit override the foreground here?
shouldnt it just work out of box (from the implicit style)?

2023-08-21 12:59 UTC, Marc-Antoine-Soucy commented on src/samples/UWP/Uno.Themes.Samples.Shared/Content/OverviewPage.xaml
This is not for testing. The reason for these changes is just to keep the text color consistent. The default text color of 
 the BodySmall style is some sort of black, which is not something we want to change, I think. The new default text color of radio buttons and checkbox (and also the one on figma) is OnSurfaceMediumBrush. 

The original bug was about the text beside the ToggleSwitch being different than the other texts. The bug was about the font being weight being different, and not the color, but I thought it would probably be better to just have all the text being the same. I can revert those changes if you think that's a bad idea.

2023-08-21 18:23 UTC, kazo0 commented on src/samples/UWP/Uno.Themes.Samples.Shared/Content/OverviewPage.xaml
We can leave the header textblocks as is, its ok if they don't match

2023-08-21 18:23 UTC, kazo0 approved these changes

2023-08-21 19:53 UTC, agneszitte commented
I added some comments for @NVLudwig where in the Uno Material Figma file seems that the colors are not correct for Disabled and also I think that it should match for both RadioButton + CheckBox

2023-08-21 19:54 UTC, agneszitte requested changes
I added some comments for @NVLudwig where in the Uno Material Figma file seems that the colors are not correct for Disabled and also I think that it should match for both RadioButton + CheckBox

2023-08-21 22:28 UTC, agneszitte requested changes

2023-08-21 22:28 UTC, agneszitte commented on src/library/Uno.Material/Styles/Controls/v2/RadioButton.xaml
> +			<StaticResource x:Key="RadioButtonOuterEllipseStrokeDisabled" ResourceKey="OnBackgroundDisabledBrush" />
@Marc-Antoine-Soucy I think the ellipses colors needs an update also for Disable State please
![image](https://github.com/unoplatform/Uno.Themes/assets/16295702/8177a8fb-9711-4430-b315-11e2f2f7bbb2)

2023-08-23 22:27 UTC, agneszitte commented
Additional changes coming to fix RadioButton & CheckBox

2023-08-28 15:56 UTC, closed without merging

2023-08-28 16:00 UTC, agneszitte commented
Closed this PR and opened https://github.com/unoplatform/Uno.Themes/pull/1167 as it contains more fixes for additional controls in addition to checkbox + radiobutton to match the latest uno material figma file