feat: add lightweight styling resources to RatingControl
unoplatform/Uno.Themes pull request #1208
Opened 2023-09-18 18:52 UTC by Arieldelossantos

﻿GitHub Issue: https://github.com/unoplatform/uno.csharpmarkup/issues/308

## PR Type

What kind of change does this PR introduce?

- Feature

## Description

## PR Checklist 
Please check if your PR fulfills the following requirements:

- Commits must be following the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- [ ] Tested the changes where applicable:
	- [ ] UWP
	- [ ] iOS
	- [ ] Android
	- [ ] WASM
	- [ ] MacOS
- [ ] Updated the documentation as needed:
	- [ ] [General Doc Update](https://github.com/unoplatform/Uno.Themes/tree/master/doc)
	- [ ] [material-controls-styles.md](https://github.com/unoplatform/Uno.Themes/blob/master/doc/material-controls-styles.md)
	- [ ] [cupertino-controls-styles.md](https://github.com/unoplatform/Uno.Themes/blob/master/doc/cupertino-controls-styles.md)
	- [ ] [lightweight-styling.md (LightWeight Styling Resource Keys)](https://github.com/unoplatform/Uno.Themes/blob/master/doc/lightweight-styling.md)
- [x] Contains **No** breaking changes
  > If the pull request contains breaking changes, commit message must contain a detailed description of the action to take for the consumer of this library. As explained by the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)

2023-09-22 16:12 UTC, ramezgerges requested changes

2023-09-22 16:12 UTC, ramezgerges commented on src/library/Uno.Themes.WinUI.Markup/Theme/RatingControl.cs
> +						public static ResourceValue<Brush> Unselected => new("RatingControlForegroundUnselected", true);
```suggestion
						public static ResourceValue<Brush> Unselected => new("SecondaryRatingControlForegroundUnselected", true);
```

And the same for everything in `Secondary`

2023-09-22 16:12 UTC, ramezgerges commented on src/library/Uno.Themes.WinUI.Markup/Theme/RatingControl.cs
> +						[ResourceKeyDefinition(typeof(Brush), "SecundaryRatingControlForegroundUnselected")]
```suggestion
						[ResourceKeyDefinition(typeof(Brush), "SecondaryRatingControlForegroundUnselected")]
```

And the same for most of `Secondary`

2023-09-22 16:20 UTC, ramezgerges commented on src/library/Uno.Themes.WinUI.Markup/Theme/RatingControl.cs
> +					}
This doesn't need a class.
```suggestion
						[ResourceKeyDefinition(typeof(Brush), "RatingControlCaptionForeground")]
						public static ResourceValue<Brush> CaptionForeground => new("RatingControlCaptionForeground", true);
```

2023-09-23 02:38 UTC, kazo0 commented on src/library/Uno.Themes.WinUI.Markup/Theme/RatingControl.cs
> +				public static class Secundary
```suggestion
				public static class Secondary
```

2023-09-23 02:38 UTC, kazo0 commented on src/library/Uno.Material/Styles/Controls/v2/RatingControl.xaml
>  ﻿<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
Make sure to update the docs of the lightweight styling keys for RatingControl

2023-09-28 18:19 UTC, kazo0 approved these changes

2023-09-29 18:49 UTC, merged