fix!: adjust brushes opacities
unoplatform/Uno.Themes pull request #1261
Opened 2023-10-27 13:35 UTC by Darsh0307

﻿GitHub Issue: close https://github.com/unoplatform/Uno.Themes/issues/1236

## PR Type

What kind of change does this PR introduce?

- [x] Documentation content changes

## Description

Replacing  the DisabledLow opacity with Disabled

## PR Checklist 
Please check if your PR fulfills the following requirements:

- Commits must be following the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- [ ] Tested the changes where applicable:
	- [ ] UWP
	- [ ] iOS
	- [ ] Android
	- [ ] WASM
	- [ ] MacOS
- [] Updated the documentation as needed:
	- [x] [General Doc Update](https://github.com/unoplatform/Uno.Themes/tree/master/doc)
	- [ ] [material-controls-styles.md](https://github.com/unoplatform/Uno.Themes/blob/master/doc/material-controls-styles.md)
	- [ ] [cupertino-controls-styles.md](https://github.com/unoplatform/Uno.Themes/blob/master/doc/cupertino-controls-styles.md)
	- [ ] [lightweight-styling.md (LightWeight Styling Resource Keys)](https://github.com/unoplatform/Uno.Themes/blob/master/doc/lightweight-styling.md)
- [x] Contains **No** breaking changes
  > If the pull request contains breaking changes, commit message must contain a detailed description of the action to take for the consumer of this library. As explained by the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)

## Other information

## Internal Issue (If applicable):

2023-10-27 17:51 UTC, Xiaoy312 reviewed
rename commit to:
fix!: adjust brushes opacities

2023-10-30 16:41 UTC, Darsh0307 commented
@Xiaoy312  I did checked the commit message accordingly.

2024-03-03 05:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/unoplatform/Uno.Themes?pullRequest=1261) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/unoplatform/Uno.Themes?pullRequest=1261) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Darsh0307<br/>:x: Darsh Patel<br/><hr/>**Darsh Patel** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/unoplatform/Uno.Themes?pullRequest=1261) it.</sub>

2024-03-04 22:36 UTC, agneszitte reviewed
Waiting on @NVLudwig's confirmation for the opacities values before we can merge this PR

2024-03-06 22:03 UTC, Xiaoy312 requested changes

2024-03-06 22:03 UTC, Xiaoy312 commented on src/library/Uno.Themes/Styles/Applications/Common/SharedColors.xaml
should change the value of DisabledLowOpacity instead of referring to DisabledOpacity

2024-03-06 22:03 UTC, Xiaoy312 commented on src/library/Uno.Themes/Styles/Applications/Common/SharedColors.xaml
also if said value was changed (or with current change in this file), there is no need to update [button,fab,nav-view,pbox].xaml in the disabled-low brush will have the same value as disabled brushes

2024-03-06 22:03 UTC, Xiaoy312 commented on doc/material-colors.md
> +| Key                | Value |
```suggestion

| Key                | Value |
```

2024-03-22 15:40 UTC, Xiaoy312 commented
to be replaced by #1369

2024-03-22 19:28 UTC, agneszitte commented
Closing this PR as the changes were done in https://github.com/unoplatform/Uno.Themes/pull/1369

2024-03-22 19:28 UTC, closed without merging